// Central data source for all localities & projects.
// Each project links out to its own microsite (external URL) as requested.

export const locations = [
  {
    id: 'panvel',
    name: 'Panvel',
    img: '/project-cards-images/hiranandani-panvel-banner.webp',
    tagline: 'Gateway to Navi Mumbai International Airport',
    blurb:
      'Panvel is emerging as a major growth corridor in Navi Mumbai, driven by the upcoming Navi Mumbai International Airport, Atal Setu and multiple metro and rail connections.',
  },

  {
    id: 'kharghar',
    name: 'Kharghar',
    tagline: "Navi Mumbai's Green, Hill-Facing Township",
    img: '/project-cards-images/saiworld-kharghar.webp',
    blurb:
      'Kharghar is a well-established CIDCO-planned node known for wide roads, Central Park, schools, hospitals and strong residential infrastructure.',
  },

  {
    id: 'seawoods',
    name: 'Seawoods',
    tagline: 'Premium Harbour-Line Address',
    img: '/project-cards-images/deltapalmbeach-seawoods-gallery1.webp',
    blurb:
      'Seawoods is a premium residential destination with excellent railway connectivity, Grand Central Mall and access to Palm Beach Road.',
  },

  {
    id: 'nerul',
    name: 'Nerul',
    tagline: 'Premium Residential Destination',
    img: '/project-cards-images/saidevelopers-nerul.webp',
    blurb:
      'Nerul offers established residential infrastructure, excellent connectivity, schools, hospitals and premium housing options.',
  },

  {
    id: 'vashi',
    name: 'Vashi',
    tagline: "Navi Mumbai's Original Business Hub",
    img: '/project-cards-images/godrej-varanya-kharghar.webp',
    blurb:
      'Vashi is one of Navi Mumbai’s most established business and residential destinations with excellent railway, road and commercial connectivity.',
  },

  {
    id: 'sanpada',
    name: 'Sanpada',
    tagline: 'Established Residential & Business Node',
    img: '/project-cards-images/godrej-sanpada-gallery1.webp',
    blurb:
      'Sanpada is a mature residential node with convenient railway connectivity, schools, commercial facilities and easy access to Palm Beach Road.',
  },

  {
    id: 'ulwe',
    name: 'Ulwe',
    tagline: 'Fast-Growing Node Near Navi Mumbai Airport',
    img: '/project-cards-images/tulipinfra-ulwe.webp',
    blurb:
      'Ulwe is a rapidly developing residential node located near the Navi Mumbai International Airport and upcoming infrastructure corridors.',
  },
];

export const properties = [
  // Panvel
  {
  id: 'hiranandani-fortune-city',
  name: 'Hiranandani Fortune City',
  developer: 'Hiranandani Group',
  location: 'panvel',
  localityLabel: 'Panvel',
  type: 'Township',
  priceRange: '₹1.31 Cr – On Request',
  beds: '2, 3 & 4 BHK',
  area: '723 – 1,896 sq.ft',
  possession: 'Ready & Under Construction Phases',
  tag: 'Iconic Township',
  tagColor: 'bg-blue-600',

  // NORMAL PROPERTY IMAGE
  img: '/project-cards-images/hiranandani-panvel.webp',

  url: 'https://hiranandani-fortunecity-panvel.in',

  highlights: [
    '5 min from Panvel Railway Station',
    'Clubhouse, schools & hospital on campus',
    'Multi-tower gated township'
  ],
},
  {
    id: 'godrej-panvel',
    name: 'Godrej Panvel',
    developer: 'Godrej Properties',
    location: 'panvel',
    localityLabel: 'Panvel',
    type: 'Apartment',
    priceRange: '₹58L – ₹1.4 Cr',
    beds: '2 & 3 BHK',
    area: '380 – 780 sq.ft',
    possession: 'Under Construction',
    tag: 'New Launch',
    tagColor: 'bg-green-500',
    img: '/project-cards-images/Godrej-City-Aerophase-Panvel-banner.webp',
    url: 'https://www.godrejproperties.com/',
    highlights: ['Close to proposed Airport corridor', 'Godrej-grade construction quality', 'Strong rental demand zone'],
  },

  // Kharghar
  {
    id: 'godrej-varanya-kharghar',
    name: 'Godrej Varanya',
    developer: 'Godrej Properties',
    location: 'kharghar',
    localityLabel: 'Kharghar',
    type: 'Apartment',
    priceRange: '₹2.14 Cr  – ₹3.79 Cr ',
    beds: '2 & 3 BHK',
    area: '725 – 1,200 sq.ft',
    possession: 'Under Construction',
    tag: 'Hot Deal',
    tagColor: 'bg-[#C9970C]',
    img: '/project-cards-images/godrej-varanya-kharghar.webp',
    url: 'https://godrej-varanya-kharghar.co',
    highlights: ['Forest-facing residences', 'Walk to Central Park, Kharghar', 'Large clubhouse & sports deck'],
  },
  {
    id: 'sai-world-empire-kharghar',
    name: 'Sai World Empire',
    developer: 'Sai Group',
    location: 'kharghar',
    localityLabel: 'Kharghar',
    type: 'Apartment',
    priceRange: '₹1.92 Cr – ₹5.24 Cr',
    beds: '2 ,3  & 4 BHK',
    area: '828 – 2140 sq.ft',
    possession: 'Ready to Move',
    tag: 'Ready to Move',
    tagColor: 'bg-blue-600',
    img: '/project-cards-images/saiworld-kharghar.webp',
    url: 'https://www.saiworldsempire.com/',
    highlights: ['Established Kharghar micro-market', 'Metro station within reach', 'High rental occupancy'],
  },
  {
    id: 'metro-satyam-kharghar',
    name: 'Metro Satyam',
    developer: 'Metro Group',
    location: 'kharghar',
    localityLabel: 'Kharghar',
    type: 'Apartment',
    priceRange: '₹1.23 Cr – ₹2.12 Cr',
    beds: '2 & 3 BHK',
    area: '	682 – 1166 sq.ft',
    possession: 'Under Construction',
    tag: 'New Launch',
    tagColor: 'bg-green-500',
    img: '/project-cards-images/metrosatyam-kharghar.webp',
    url: 'https://metro-satyam-kharghar.in',
    highlights: ['Adjacent to Kharghar metro line', 'Compact, efficient layouts', 'Good entry-level ticket size'],
  },
  {
    id: 'gami-bhagwati-kharghar',
    name: 'Gami Bhagwati',
    developer: 'Gami Group',
    location: 'kharghar',
    localityLabel: 'Kharghar',
    type: 'Apartment',
    priceRange: '₹1.55 Cr – ₹2.50 Cr',
    beds: '2 & 3 BHK',
    area: '810 – 963 sq.ft',
    possession: 'Under Construction',
    tag: 'Hot Deal',
    tagColor: 'bg-[#C9970C]',
    img: '/project-cards-images/gamibhagwati-kharghar.webp',
    url: 'https://gami-bhagwati-kharghar.in',
    highlights: ['Gami Group\'s signature quality', 'Landscaped podium gardens', 'Close to Kharghar valley'],
  },

  // Seawoods - Nerul
  {
    id: 'delta-seawoods',
    name: 'Delta',
    developer: 'Palm Beach Group',
    location: 'seawoods',
    localityLabel: 'Seawoods',
    type: 'Apartment',
    priceRange: '₹2.90 Cr – ₹6.06 Cr ',
    beds: '2, 3 & 4 BHK',
    area: '844 – 1,774 sq.ft',
    possession: 'Ready & Under Construction',
    tag: 'Top Selling',
    tagColor: 'bg-blue-600',
    img: '/project-cards-images/deltapalmbeach-seawoods.webp',
    url: 'https://palmbeach-seawoods.in',
    highlights: ['Walk to Grand Central Mall', 'Harbour-line & NMMT connectivity', 'Premium sea-facing towers'],
  },
  {
    id: 'gami-palm-amore-seawoods',
    name: 'Gami Palm Amore',
    developer: 'Gami Group',
    location: 'seawoods',
    localityLabel: 'Seawoods',
    type: 'Apartment',
    priceRange: '₹2.80 Cr – ₹6.70 Cr',
    beds: '2, 3 & 4 BHK',
    area: '856  – 1690 sq.ft',
    possession: 'Under Construction',
    tag: 'New Launch',
    tagColor: 'bg-green-500',
    img: '/project-cards-images/gamipalmamore-seawoods.webp',
    url: 'https://gami-palmamore-seawoods.com',
    highlights: ['Resort-style clubhouse', 'Minutes from Seawoods station', 'Strong appreciation track record'],
  },

    // Seawoods - Nerul 
    
  {
    id: 'pyramid-centria-nerul',
    name: 'Pyramid Centria',
    developer: 'Pyramid Group',
    location: 'nerul',
    localityLabel: 'Nerul',
    type: 'Apartment',
    priceRange: '₹1.90 Cr – ₹3.10 Cr',
    beds: '2 & 3 BHK',
    area: '714 – 1,122  sq.ft',
    possession: 'Ready to Move',
    tag: 'Ready to Move',
    tagColor: 'bg-blue-600',
    img: '/project-cards-images/Pyramid-Centria-banner.webp',
    url: 'https://pyramid-centria-nerul.in',
    highlights: ['Premium high-rise skyline views', 'Large clubhouse & sky lounge', 'Walk to Seawoods-Darave station'],
  },
  {
    id: 'matrix-nerul',
    name: 'Matrix',
    developer: 'Matrix Group',
    location: 'nerul',
    localityLabel: 'Nerul',
    type: 'Apartment',
    priceRange: '₹2.11 Cr – ₹2.71 Cr',
    beds: '2 & 3 BHK',
    area: '748 – 980 sq.ft',
    possession: 'Under Construction',
    tag: 'Hot Deal',
    tagColor: 'bg-[#C9970C]',
    img: '/project-cards-images/matrixnerul.webp',
    url: 'https://matrix-nerul.in',
    highlights: ['Efficient carpet-to-built ratio', 'Close to Nerul market & schools', 'Good rental yield micro-market'],
  },
  {
    id: 'sai-developers-nerul',
    name: 'Paradise Saipalmview Nerul',
    developer: 'Sai Developers',
    location: 'nerul',
    localityLabel: 'Nerul',
    type: 'Apartment',
    priceRange: '₹11.25 Cr – ₹12.75 Cr',
    beds: '4 BHK Residences',
    area: '	4075 Sq.Ft.',
    possession: 'Under Construction',
    tag: 'New Launch',
    tagColor: 'bg-green-500',
    img: '/project-cards-images/saidevelopers-nerul.webp',
    url: 'https://saidevelopers-nerul.in',
    highlights: ['Trusted local developer', 'Value-for-money entry price', 'Close to Seawoods Grand Central'],
  },
  
  // Vashi - Sanpada
  {
    id: 'godrej-vashi-bayview',
    name: 'Godrej Vashi Bayview',
    developer: 'Godrej Properties',
    location: 'vashi',
    localityLabel: 'Vashi',
    type: 'Apartment',
    priceRange: '₹3.27 Cr – ₹4.37 Cr Onwards',
    beds: '2 & 3 BHK',
    area: '874 – 1,268 sq.ft',
    possession: 'Under Construction',
    tag: 'Premium',
    tagColor: 'bg-blue-600',
    img: '/project-cards-images/godrej-vashi-bayview.webp',
    url: 'https://godrej-vashi-bayview.in',
    highlights: ['Creek & bay-facing residences', 'Steps from Vashi railway station', 'Godrej quality & trust'],
  },
  {
    id: 'godrej-sanpada',
    name: 'Godrej Sanpada – Eternal Palms',
    developer: 'Godrej Properties',
    location: 'sanpada',
    localityLabel: 'Sanpada',
    type: 'Apartment',
    priceRange: '₹ 324 Cr – ₹ 434 Cr',
    beds: '2 & 3 BHK',
    area: '809 – 1,000 sq.ft',
    possession: 'Ready & Under Construction',
    tag: 'Ready to Move',
    tagColor: 'bg-blue-600',
    img: '/project-cards-images/godrej-sanpada-eternalpalms.webp',
    url: 'https://eternal-palms-sanpada.in',
    highlights: ['Tree-lined Sanpada sectors', 'Top schools within walking distance', 'Established, liquid resale market'],
  },

  // Ulwe
  {
    id: 'tulip-kingdom-ulwe',
    name: 'Tulip Kingdom',
    developer: 'Tulip Infra',
    location: 'ulwe',
    localityLabel: 'Ulwe',
    type: 'Apartment',
    priceRange: '₹ 1.11 Cr  – ₹ 1.55 Cr + Taxes',
    beds: '2 & 3 BHK',
    area: '671 – 1021 sq.ft',
    possession: 'Under Construction',
    tag: 'New Launch',
    tagColor: 'bg-green-500',
    img: '/project-cards-images/tulipinfra-ulwe.webp',
    url: 'https://tulipinfra-ulwe.in',
    highlights: ['Opposite Navi Mumbai Intl. Airport', 'Fastest appreciating node in NM', 'Entry-level ticket size for NRIs'],
  },
  {
    id: 'progressive-ulwe',
    name: 'Progressive Heights',
    developer: 'Progressive Group',
    location: 'ulwe',
    localityLabel: 'Ulwe',
    type: 'Apartment',
    priceRange: '₹ 2.40 Cr – ₹ 7.50 Cr',
    beds: '3, 3.5 & 4.5 BHK',
    area: '1000 – 2480 sq.ft',
    possession: 'Under Construction',
    tag: 'Hot Deal',
    tagColor: 'bg-[#C9970C]',
    img: '/project-cards-images/progressive-ulwe-gallery1.webp',
    url: 'https://www.progressivegroup.in/progressives-grande.html',
    highlights: ['Near Ulwe metro corridor', 'Modern amenities & clubhouse', 'High rental potential post airport'],
  },
  {
    id: 'the-domus-ulwe',
    name: 'The Domus',
    developer: 'Domus Realty',
    location: 'ulwe',
    localityLabel: 'Ulwe',
    type: 'Apartment',
    priceRange: '₹ 62 Lacs – ₹ 1.48 Cr',
    beds: '1, 2 & 3 BHK',
    area: '433 – 1017 sq.ft',
    possession: 'Under Construction',
    tag: 'New Launch',
    tagColor: 'bg-green-500',
    img: '/project-cards-images/domusulwe.webp',
    url: 'https://thedomus-ulwe.in',
    highlights: ['Boutique low-density development', 'Close to Ulwe Sector 19 hub', 'Designed for NRI end-users'],
  },
]

export function getPropertiesByLocation(locationId) {
  return properties.filter((p) => p.location === locationId)
}
